# Generated by Django 6.1 on 2026-08-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tiltle',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='General', max_length=255, verbose_name='عنوان التصنيف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'قيد التجهيز'), ('S', 'تم الشحن'), ('D', 'تم التوصيل'), ('C', 'ملغى')], default='P', max_length=1, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'قيد الانتظار'), ('C', 'مكتمل'), ('F', 'فشل الدفع')], default='P', max_length=1, verbose_name='حالة الدفع'),
        ),
    ]
