# Generated by Django 6.1 on 2026-08-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='api/images', verbose_name='صورة المنتج'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
